### ISSUE TITLE
Release a new version to crates.io

### ISSUE THREAD

**Issue by sfackler** [BurntSushi/byteorder#10]
Can you release a new version with the change from #9?

**Comment by BurntSushi** [comment]
Hmm... I'd love to. I just updated to the latest nightly, and it seems my Cargo is broken?

```
[andrew@Liger byteorder] cargo build --verbose
Process didn't exit successfully: `rustc - --crate-name - --crate-type dylib --crate-type bin --print=file-names` (status=101)
--- stderr
error: crate name cannot start with a hyphen: -
error: aborting due to previous error
```

It looks like `--crate-name` is messed up? Weird. (I've done `cargo clean`.)

Versions:

```
[andrew@Liger byteorder] rustc --version
rustc 1.0.0-nightly (c4fe7d6ae 2015-02-23) (built 2015-02-24)
[andrew@Liger byteorder] cargo --version
cargo 0.0.1-pre-nightly (43755c0 2015-02-19) (built 2015-02-21)
```

I'm at work now, so unfortunately I can't do much more investigation then this...

**Comment by BurntSushi** [comment]
Yup, it's really broken. Grrr. http://users.rust-lang.org/t/psa-the-2015-02-25-nightly-contains-a-broken-cargo/455

**Comment by BurntSushi** [comment]
Ah finally. Release `0.2.10`.

**Comment by sfackler** [comment]
Thanks!
