### ISSUE TITLE
implement try_write_u64 etc. with behavior like std::io::Write::write

### ISSUE THREAD

**Issue by vks** [BurntSushi/byteorder#100]
Unlike `write_u64`, `try_write_u64` should return `Ok(n)`, where `n` is the number of written bytes. This is the same behavior as `std::io::Write::write`.

A use case is the implementation of `rand::Rng::fill_bytes` for a RNG generating `u64`.

**Comment by BurntSushi** [comment]
I don't feel particularly inclined to double the size of the API. The `Write` methods *must* return an error. Why is a contract violation insufficient for the `ByteOrder` trait?

**Comment by vks** [comment]
You are right, the current methods actually are sufficient.
