### ISSUE TITLE
u24{le, be} to u32 support

### ISSUE THREAD

**Issue by brendanzab** [BurntSushi/byteorder#108]
I'm currently building a binary data definition language, and bottom out by calling out to `byteorder`. Many formats require support for u24s though, so I end up having to do:

```rust
#[inline]
pub fn from_u24le<R: Read>(r: &mut R) -> io::Result<u32> {
    let mut buf = [0u8; 3];
    r.read_exact(&mut buf)?;
    Ok(((buf[0] as u32) << 0) | ((buf[1] as u32) << 8) | ((buf[2] as u32) << 16))
}

#[inline]
pub fn from_u24be<R: Read>(r: &mut R) -> io::Result<u32> {
    let mut buf = [0u8; 3];
    r.read_exact(&mut buf)?;
    Ok(((buf[2] as u32) << 0) | ((buf[1] as u32) << 8) | ((buf[0] as u32) << 16))
}

#[inline]
pub fn from_i24le<R: Read>(r: &mut R) -> io::Result<i32> {
    let mut buf = [0u8; 3];
    r.read_exact(&mut buf)?;
    Ok(((buf[0] as i32) << 0) | ((buf[1] as i32) << 8) | ((buf[2] as i32) << 16))
}

#[inline]
pub fn from_i24be<R: Read>(r: &mut R) -> io::Result<i32> {
    let mut buf = [0u8; 3];
    r.read_exact(&mut buf)?;
    Ok(((buf[2] as i32) << 0) | ((buf[1] as i32) << 8) | ((buf[0] as i32) << 16))
}
```

Would be nice to have suppport in `byteorder` for this, instead of me having to write out this error-prone code. I know you have quickcheck running on this, which is great, as well as some performance tuning, and it'd be nice to take advantage of that.

I know you have `read_uint` and `read_int` (as mentioned in #38), but those output to `u64`s and `i64`s respectively. Any chance of having an API that is specialised to output to the smallest possible Rust primitive - ie. `u32` and `i32`?

**Comment by BurntSushi** [comment]
Can you explain why specifically read_uint is insufficient? i.e., Why can't you cast the result to the desired type? Like, I'm not getting why you didn't just implement your helper functions using read_uint in the first place?

**Comment by brendanzab** [comment]
Hmm, right! I'm guessing I could do that.

Would be interesting to compare the optimized output and performance of `read_uint::<BigEndian>(3).map(|x| x as u32)` to something that uses your internal macro 🤔.

**Comment by brendanzab** [comment]
Bit hard to say anything without numbers. But even if it isn't as fast, at least it has more of a chance of being correct than my hand-coded stuff!

**Comment by brendanzab** [comment]
If you're wondering what my thought process it was:

1. read the library docs, couldn't find `read_u24`, so figured I needed to write it myself
2. looked at the source code of byteorder, then decided to follow Rob Pike's blog post instead, rather than dealing with the stuff that the internal macros do
3. found the #38, as I was making this issue, then realized that `read_{uint,int}` only output to `{u64,i64}`.
4. programmer fail in not proceeding to pull `byteorder` and attempt to compare the performance of a lower level implementation of `read_u24`->`u32` and just casting in a `Result::map`.

So yes, partly my fault in not stopping writing my issue and going straight to measuring as soon as I found `read_{uint,int}`.

I am wondering if there is an issue in that I missed those two methods, but perhaps that's because I read them as `read{usize,isize}`. I'm a pre-rust 1.0 programmer so I might have got my wires crossed and assumed they were reading pointer-sized integers.

So yes, I can close this issue and come back with numbers if you like.

**Comment by BurntSushi** [comment]
@brendanzab Aye, sounds good. And yeah, byteorder has a ton of methods servicing various use cases. The more we have, the harder it is to find what you want, so that's why I try to push back on additions like these. :-)

But yeah feel free to re-open if you discover anything interesting!
