### ISSUE TITLE
Use IntoIterator instead of slices

### ISSUE THREAD

**Issue by punkkeks** [BurntSushi/byteorder#111]
Wouldn't it be handy to accept an iterator instead of a slice? Maybe like:

    fn read_u32<T: IntoIterator>(buf: &T) -> u32;
    fn write_u32<T: IntoIterator>(buf: &mut T, n: u32);

Maybe if you really need the amount of items of `T` you may use [`ExactSizeIterator`](https://doc.rust-lang.org/std/iter/trait.ExactSizeIterator.html) instead of plain IntoIterator.

**Comment by BurntSushi** [comment]
No, sorry, this doesn't work. A fast implementation needs a slice.

**Comment by punkkeks** [comment]
Alright, I can accept that argument ;)
