### ISSUE TITLE
Encoding u64 to u48 bytes

### ISSUE THREAD

**Issue by sharksforarms** [BurntSushi/byteorder#118]
Is this possible using the API and not having to popthe excess?

I can do
```
result.write_u64<LittleEndian>(123123);
result.pop();
result.pop();
```

But it'd be cool if I didn't need to and could just write it out as a u48 (6 bytes)

**Comment by BurntSushi** [comment]
Why doesn't `write_uint` solve your problem?

**Comment by sharksforarms** [comment]
Ahh must have missed that one. Thanks.
