### ISSUE TITLE
Use io::Result instead of customized Result

### ISSUE THREAD

**Issue by zonyitoo** [BurntSushi/byteorder#12]
I think the APIs should return `io::Result` instead of `byteorder::Result`. It would be much easier to migrate those libs who depend on old_io to new io.

I suggest the `UnexpectedEOF` error could be put into the `io::Error` with `io::ErrorKind::Other` kind.

I could submit a PR.

**Comment by zonyitoo** [comment]
It seems that commit dc6a8670394134d1f4c831d1d04eddc476cf785e have implemented `std::error::FromError` for `io::Error`.

Please push this to crates.io. ;)

**Comment by BurntSushi** [comment]
I'd love to push to `crates.io`. Yesterday, Cargo was broken. Today, `log` is broken. (It seems a fixed was just merged, but hasn't been updated in crates.io yet: https://github.com/rust-lang/log/pull/25)

I'm at work, so I don't have time to fiddle with rolling back `rustc` on my machine.
