### ISSUE TITLE
Support for SIMD types

### ISSUE THREAD

**Issue by vks** [BurntSushi/byteorder#126]
It would be nice to support `__m128`, `__m256`, `__m128d`, `__m128i`, `__m256d`, `__m256i`, etc. the same way the primitive integers are supported.

**Comment by BurntSushi** [comment]
I'm not so sure about this. Or at the very least, I'd rather wait and let the SIMD stuff bake for a bit to make sure we get it right. There's also an extra complication: with SIMD, you're liable to care about alignment, and byteorder currently does exclusively unaligned loads and stores.

**Comment by vks** [comment]
There might also be some overlap with `core::simd::FromBits`.

**Comment by BurntSushi** [comment]
I don't think byteorder should care about platform specific types like this. Vendor intrinsics are already available for converting pointers to vectors. They are unsafe, sure, but when you're working with types like `__m128i`, then you likely have a lot of surrounding unsafe code.

If and when platform independent vector types are stabilized then we can perhaps revisit this, but my guess is that most cases will indeed already be handled by things like `FromBits`.
