### ISSUE TITLE
u128 is stable

### ISSUE THREAD

**Issue by james-darkfox** [BurntSushi/byteorder#136]
https://doc.rust-lang.org/stable/std/primitive.u128.html

https://github.com/BurntSushi/byteorder/blob/master/Cargo.toml#L26

**Comment by BurntSushi** [comment]
This isn't an actionable ticket. I don't know what you're asking me to do. Please consider being more explicit about the problem you're trying to solve.

**Comment by james-darkfox** [comment]
@BurntSushi Sorry. The feature is unnecessary and may be removed as stable rust supports it.

**Comment by james-darkfox** [comment]
@BurntSushi Okay, fair reason. No actual problem, just didn't realize the minimum supported version and thought it was unnecessary. My bad, I target nightly and just smile when my code runs on stable. ;)

Thanks for the quick response.
