### ISSUE TITLE
literal out of range 

### ISSUE THREAD

**Issue by Dylan-DPC** [BurntSushi/byteorder#144]
The current build fails with: 
```
error: literal out of range for i16
[INFO] [stdout]  --> src/lib.rs:1603:23
[INFO] [stdout]   |
[INFO] [stdout] 6 | let mut numbers = [5, 65000];
[INFO] [stdout]   |                       ^^^^^
```

picked this up from a crater run

**Comment by BurntSushi** [comment]
We should definitely fix this, but this seems like a bug with Rust nightly. Overflowing integer literals shouldn't cause compilation failures on Rust 2015. It was only switched to `deny` in Rust 2018: https://github.com/rust-lang/rfcs/blob/master/text/2438-deny-integer-literal-overflow-lint.md

**Comment by Dylan-DPC** [comment]
Thanks. Will create an issue upstream (if it doesn't exist)

**Comment by ehuss** [comment]
`overflowing_literals` was switched to deny in 2015 in https://github.com/rust-lang/rust/pull/55632.
