### ISSUE TITLE
Improved write_u64 performance

### ISSUE THREAD

**Issue by velvia** [BurntSushi/byteorder#149]
I have a mini benchmark for a bit packing/compression algorithm which uses `write_u64` from `WriteBytesExt`.  The benchmark results show about a 2x speedup when I replace `write_u64` with an unsafe equivalent.  This issue is to track to understand why this is, and if we can/should do anything abut it.

Repo:  http://github.com/filodb/compressed_vec

Standard write_u64 code:  in branch `2d-delta-safe2`
To invoke benchmark: `cargo bench -- "nibblepack8"`

```
nibblepack8 varying # bits/8
                        time:   [40.261 ns 40.711 ns 41.252 ns]
                        change: [+76.426% +77.835% +79.411%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 9 outliers among 100 measurements (9.00%)
  3 (3.00%) high mild
  6 (6.00%) high severe
nibblepack8 varying # bits/12
                        time:   [26.229 ns 26.456 ns 26.746 ns]
                        change: [+5.7323% +6.5387% +7.3247%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 11 outliers among 100 measurements (11.00%)
  1 (1.00%) low severe
  2 (2.00%) low mild
  5 (5.00%) high mild
  3 (3.00%) high severe
nibblepack8 varying # bits/16
                        time:   [39.930 ns 40.063 ns 40.225 ns]
                        change: [+76.888% +78.479% +80.410%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 11 outliers among 100 measurements (11.00%)
```

(*Note: the # bits /8 and /16 are the ones we care about, basically where number of bits are divisible by 8 as that's the path that uses write_u64)

On another branch, the unsafe code:  `2d-delta-hist`

```
nibblepack8 varying # bits/8
                        time:   [22.618 ns 22.742 ns 22.892 ns]
                        change: [-43.323% -42.881% -42.454%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 9 outliers among 100 measurements (9.00%)
  5 (5.00%) high mild
  4 (4.00%) high severe
nibblepack8 varying # bits/12
                        time:   [24.619 ns 24.681 ns 24.756 ns]
                        change: [-7.3756% -6.5124% -5.7051%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 18 outliers among 100 measurements (18.00%)
  1 (1.00%) low severe
  1 (1.00%) low mild
  7 (7.00%) high mild
  9 (9.00%) high severe
nibblepack8 varying # bits/16
                        time:   [22.519 ns 22.554 ns 22.593 ns]
                        change: [-42.832% -42.519% -42.256%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 11 outliers among 100 measurements (11.00%)
```

The code is in `byteutils.rs::direct_write_uint_le`.

The unsafe version is about 2x faster.

It's a little hard to tell from disassembly where the relevant asm is.  What I do though is that I comment out the `#[inline]` above the direct_write_uint_le func and run `cargo asm compressed_vec::byteutils::direct_write_uint_le`.

**Comment by BurntSushi** [comment]
Your repo link, https://github.com/filodb/compressed_vec, gives a 404.

**Comment by BurntSushi** [comment]
Please also provide github permalinks to the relevant code.

**Comment by velvia** [comment]
@BurntSushi ok sorry here it is.

"Safe" version using `byteorder`:

https://github.com/filodb/compressed-vec/blob/0f17c79df826e3a0f53b3afab53932b48a1ee903/src/byteutils.rs#L11

Unsafe version using unaligned ptr writes:

https://github.com/filodb/compressed-vec/blob/0a4f9f7576faa9c3135359334cf05e96c86cce39/src/byteutils.rs#L13

**Comment by BurntSushi** [comment]
Okay, so what are we trying to do here? I would naively _expect_ the unsafe version to be faster, precisely because it's doing less work: it doesn't need to do bounds checks. Also, your comments say, "which uses memcpy instead," but this is pretty misleading. I thought I mentioned this earlier, but byteorder is using the same approach to write bytes as you are. (Go look at the implementation of `write_unaligned`.)

I'd strongly advise you to look at the generated assembly code.
