### ISSUE TITLE
Add endianness type parameter for (read|write)_[ui]8

### ISSUE THREAD

**Issue by SOF3** [BurntSushi/byteorder#153]
I am using a macro to generate implementations for all primitive integer types like this:

```rust
macro_rules! gen_write {
    ($ty:ty, $write:ident) => {
        impl MyTrait for $ty {
            fn my_method<W: Write>(&self) {
                use byteorder::{BigEndian, WriteBytesExt};
                w.$write::<BigEndian>(*self);
            }
        }
    };
}
```

The lack of type parameter in the `(read|write)_[ui]8` methods caused inconsistency in my generated code. It would be useful to have them accept a dummy, unused endianness parameter.

**Comment by BurntSushi** [comment]
Sigh. I figured adding `read_u8`/`read_i8` would come back to bite me.

But no, these methods do not require endianness, so they will not get a type parameter just to make macro code easier to write. Instead, write out the one special case if you need to.
