### ISSUE TITLE
Add `read_u8_into()` for completeness

### ISSUE THREAD

**Issue by I3ck** [BurntSushi/byteorder#162]
Since `read_u8` and `read_i8` are already added for completeness, I think it makes sense to also add their `_into` variants.  
Such that instead of:  
```rust
// Drop header
for _ in 0..80 {
    read.read_u8()?;
}
```
One can use:  
```rust
// Drop header
let mut buffer = [0u8; 80];
read.read_u8_into(&mut buffer);
```  
It's possible I'm missing another solution which might resolve this issue.

**Comment by BurntSushi** [comment]
Yes. You should use [`std::io::Read::read_exact`](https://doc.rust-lang.org/std/io/trait.Read.html#method.read_exact).

**Comment by I3ck** [comment]
Yep, thank you (for the help and your libraries / programs :) )
