### ISSUE TITLE
Support async analogues of Read and Write extensions

### ISSUE THREAD

**Issue by jimblandy** [BurntSushi/byteorder#167]
It would be nice to offer extensions to the `futures` and `tokio` crates' `AsyncRead` and `AsyncWrite` traits analogous to the extensions for `std::io::Read` and `Write`.

It's true that we're hoping for those to all be unified, but that doesn't seem to be imminent.

See also the `byteorder_async` crate, which is a fork of this crate that has implemented this idea.

**Comment by BurntSushi** [comment]
I think folks should just use the forked crate for now. I'm not touching the async ecosystem right now. There are too many unknowns and the dependencies seemingly required to support it are absolutely huge. If and when std acquires async i/o traits, then we can revisit this.

**Comment by jimblandy** [comment]
Makes sense. I do hope we can get the async I/O traits into std; things are a bit weird without them.

**Comment by jmg-duarte** [comment]
@BurntSushi any interest in expanding this ~4 years later? The forked crate hasn't received updates 😞

**Comment by BurntSushi** [comment]
I'm not really interested in doing any major expansions to the `byteorder` crate at this time. If and when async I/O traits get added to `std`, then I'd be happy to build on them. But as it stands right now, there are two different `AsyncRead` traits. It's a maintenance nightmare. And this crate is at `1.0` while `futures` is not.
