### ISSUE TITLE
Add `read_u40`

### ISSUE THREAD

**Issue by Stargateur** [BurntSushi/byteorder#168]
I need to read 5 bytes number but there seem to be no way to do it. There is a `read_u24` so why not `read_u40` too ?

**Comment by BurntSushi** [comment]
I kind of regret adding `read_u24`, as I'm not convinced how common it actually is. But it was added [in this PR](https://github.com/BurntSushi/byteorder/pull/87), and its commonality as a special case was the main reason to use it.

I'm not inclined to add u40, u48, u56 and so on. This is why `read_uint` exists. Please use that instead.
