### ISSUE TITLE
Using byteorder with type definitions

### ISSUE THREAD

**Issue by dannygale** [BurntSushi/byteorder#170]
I have several type definitions that I'd like to be able to read with byteorder. For example

```
type BlockAddr = u32;
type BlockIndex = u32;
```

Right now, I use `read_32`, but as I start playing with different types, I need to go through and change all the `read_u32`'s to `read_somethingelse` each time. Is there a way to do this today?

**Comment by BurntSushi** [comment]
Macros probably. Or define your own trait.
