### ISSUE TITLE
Add "NativeEndian" byte order

### ISSUE THREAD

**Issue by netvl** [BurntSushi/byteorder#18]
Please consider adding `NativeEndian` byte order which corresponds to the byte order used on the host system.

While `NativeEndian` can be dangerous for cross-platform compatibility, sometimes it can be necessary. For example, some (poorly defined) file formats may use platform endianness for multi-byte numbers.

**Comment by TyOverby** [comment]
:+1:

**Comment by BurntSushi** [comment]
No convincing needed. I want this. It can also be useful for performance reasons when your format is not meant to be portable. (Say, a database writing to disk.)
