### ISSUE TITLE
Any difference to Rust official functions?

### ISSUE THREAD

**Issue by oilel** [BurntSushi/byteorder#190]
The developers of Rust has provided to_be_bytes(), to_le_bytes(), and to_ne_bytes(), should we still need this 3rd-party crate?

**Comment by BurntSushi** [comment]
This crate was _never_ necessary.

There are more APIs in this crate than things like `to_le_bytes`. Whether they're useful to you or not is up to you. Since you didn't elaborate on your use case, it's impossible for me to say more.
