### ISSUE TITLE
use of undeclared trait name `Writer`/'Reader'

### ISSUE THREAD

**Issue by lambdaburrito** [BurntSushi/byteorder#20]
My Cargo.toml file looks like this:

    [package]

    name = "lambda-db"
    version = "0.0.1"
    authors = ["asdasd < asdasd@gmail.com>"]

    [dependencies]
    bincode = "*"

I'm using the lastest rustc compile:
    rustc 1.0.0-nightly (b0aad7dd4 2015-03-22) (built 2015-03-23)

However I am getting build errors as it's missing undeclared trait names - Reader and Writer.

    error: use of undeclared trait name `Writer`
    /home/pez/.cargo/registry/src/github.com-1ecc6299db9ec823/byteorder-0.2.14/src/old.rs:225 impl<W: Writer> WriterBytesExt for W {}

**Comment by BurntSushi** [comment]
You are using an old version of `byteorder`. Please run `cargo update`.

**Comment by lambdaburrito** [comment]
I have updated and cleaned out ~/.cargo too..

**Comment by lambdaburrito** [comment]
It looks like bincode is using binorder 0.2.* as a dependency; should it be using 0.3.* instead?

**Comment by BurntSushi** [comment]
Yes. `0.2.*` has support for `std::old_io`, which is apparently broken now.
