### ISSUE TITLE
[Bug] Some unknown error caused by byteorder 1.5.0

### ISSUE THREAD

**Issue by Demy076** [BurntSushi/byteorder#203]
4|product_ | range end index 4 out of range for slice of length 2
4|product_ | Error: error returned from database: cached plan must not change result type
4|product_ |
4|product_ | Caused by:
4|product_ |     cached plan must not change result type
4|product_ | thread 'tokio-runtime-worker' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/byteorder-1.5.0/src/lib.rs:1946:31:
4|product_ | range end index 4 out of range for slice of length 2

rustc 1.74.1 (a28077b28 2023-12-04)

Debian 11 ( 5.10.0-27-cloud-amd64 #1 SMP Debian 5.10.205-2 (2023-12-31) x86_64 GNU/Linux)

**Comment by BurntSushi** [comment]
Just because a panic originates in this library doesn't mean it's this library's fault. You'll need to do some debugging.
