### ISSUE TITLE
error: enum `Error` is private

### ISSUE THREAD

**Issue by Antti** [BurntSushi/byteorder#21]
I can't write my converter from `byteorder::new::Error`, i.e.:
```rust
impl FromError<byteorder::new::Error> for MyError { .. }
```

Therefore converting errors becomes a pain, and I must `map_err` every time I'm reading primitives.

**Comment by BurntSushi** [comment]
Uh. Can you please show some code?

**Comment by Antti** [comment]
Sorry, accidentally hit enter before I could write a description.

**Comment by Antti** [comment]
OK. Looking at the source code, it looks like I should have been using `byteorder::Error`, as it is `pub use new::Error`.

**Comment by BurntSushi** [comment]
Correct. In general, you should [consult the documentation](http://burntsushi.net/rustdoc/byteorder/) to figure out the paths that should be used. Many crates do not expose their internal module structure and instead craft the public interface through re-exports.
