### ISSUE TITLE
How to use the xxx_into methods?

### ISSUE THREAD

**Issue by svanharmelen** [BurntSushi/byteorder#215]
I'm struggling to understand how I can convert a `Vec` of (for example) `i32`'s using `write_i32_into` as that requires an array with an exact length.

Yet I don't know the length upfront as I will receive the `Vec` over the wire with an arbitrary number of elements. So is there a way to achieve this, or am I looking it this the wrong way and should I use a different approach?

**Comment by svanharmelen** [comment]
Guess I can do something like this:

```rust
let bytes: Vec<u8> = values
    .iter()
    .map(|v| v.to_le_bytes())
    .flatten()
    .collect();
```

But still wonder if/how the read/write into (I'm also trying to use the `read_i32_into`) methods can be used with inputs of arbitrary sizes.

**Comment by BurntSushi** [comment]
> `write_i32_into` as that requires an array with an exact length

To be clear here, `ByteOrder::write_i32_into` requires two _slices_. Slices and arrays are not the same thing. Arrays have a statically known length. Slices do not.

> Yet I don't know the length upfront as I will receive the Vec over the wire with an arbitrary number of elements. So is there a way to achieve this, or am I looking it this the wrong way and should I use a different approach?

I'm not really understanding the issue here. If `src` is a `Vec<i32>`, then you know its length via `src.len()`. And if you know its length, then you know how big the length of the `dst` slice must be. In this case, `src.len() * 4` since each `i32` uses 4 bytes. So you need to make a `dst` that has that length.

**Comment by svanharmelen** [comment]
> To be clear here, ByteOrder::write_i32_into requires two slices. Slices and arrays are not the same thing. Arrays have a statically known length. Slices do not.

Ah... So something like this should work:

```rust
// values is a Vec<i32>
let mut bytes = vec![0i32; values.len() * 4];
LittleEndian::write_i32_into(&values, &mut bytes);
```

> I'm not really understanding the issue here. If src is a Vec<i32>, then you know its length via src.len(). And if you know its length, then you know how big the length of the dst slice must be. In this case, src.len() * 4 since each i32 uses 4 bytes. So you need to make a dst that has that length.

Yes, that's all clear. I meant I didn't know the length upfront in order to be able to create an array with that length. But if using a slice is also possible then that solves the problem I guess. So probably just a skill issue on my side :wink:

**Comment by BurntSushi** [comment]
Aye. You may be able to amortize the allocation as well, but it really depends on what you're doing. For example, if you have a reusable alloc for writing bytes into, even if it's too big, you can do `&mut buffer[..values.len() * 4]` to get a smaller slice of it. But whether this makes any sense really does depend on how you're using it.
