### ISSUE TITLE
Support reading odd number of bytes

### ISSUE THREAD

**Issue by jwilm** [BurntSushi/byteorder#38]
Some protocols specify 3 byte numbers (eg u24 in [rfc5246](https://tools.ietf.org/html/rfc5246#section-4.4)), and it would be really handy if _byteorder_ supported a `read_u24` function out of the box.

**Comment by BurntSushi** [comment]
Is there any particular reason why [`read_uint`](http://burntsushi.net/rustdoc/byteorder/trait.ReadBytesExt.html#method.read_uint) or `read_int` don't work for you?

**Comment by jwilm** [comment]
Not at all! I managed to miss them while looking at the docs was the only problem :flushed:. Thanks!
