### ISSUE TITLE
Lack of read_*_uint_n, read_*_int_n

### ISSUE THREAD

**Issue by blackbeam** [BurntSushi/byteorder#4]
If there is no problem with this, then i can steal implementation from `old_io` and fill a pull request.

**Comment by BurntSushi** [comment]
Do you mean `usize` and `isize`? I am skeptical of including these because their size is tied to the size of a pointer on a machine. It seems like a bad idea to be encoding/decoding those.

**Comment by BurntSushi** [comment]
e.g., Why not just use `n as u64` or `n as i64`?

**Comment by blackbeam** [comment]
uint and int does not name a type in that case. Methods returns u64 and i64 respectively. 
They purpose is to parse 3, 5, 6 and 7 bytes integers (used in binary protocols to save some space).

**Comment by blackbeam** [comment]
Here is a link to the one of old_io methods [read_le_uint_n](http://doc.rust-lang.org/std/old_io/trait.Reader.html#method.read_le_uint_n)

**Comment by BurntSushi** [comment]
Ah, I see. How archaic is the use case? I'm OK with including it here, but that depends on how much extra code/complexity it adds. For example, I don't think you can easily reuse the `read_num_bytes` and `write_num_bytes` macros because the integer size has to be a constant.

**Comment by blackbeam** [comment]
Well.. Here it is #5.
