### ISSUE TITLE
Add impls for all of the builtin traits to LittleEndian and BigEndian and make ByteOrder also require those impls

### ISSUE THREAD

**Issue by fitzgen** [BurntSushi/byteorder#52]
Right now, making something compile-time generic over endianness is a huge pain:

``` rust
extern crate byteorder;
use byteorder::{ByteOrder, LittleEndian};

use std::marker::PhantomData;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct EndianBuf<'a, Endian>(&'a [u8], PhantomData<Endian>) where Endian: ByteOrder;

impl<'a, Endian> EndianBuf<'a, Endian> where Endian: ByteOrder {
    fn new(buf: &'a [u8]) -> EndianBuf<'a, Endian> {
        EndianBuf(buf, PhantomData)
    }
}

fn main() {
    let buf = [1,2,3,4,5,6];

    let a = EndianBuf::<LittleEndian>::new(&buf);
    let b = EndianBuf::<LittleEndian>::new(&buf);

    // Compiler error regarding this line!
    assert_eq!(a, b);
}
```

If you do `rustc -Z unstable-options --pretty expanded endian_buf.rs`, you will see this:

``` rust
#[automatically_derived]
#[allow(unused_qualifications)]
impl <'a, Endian: ::std::clone::Clone> ::std::clone::Clone for EndianBuf<'a, Endian>
    where Endian: ByteOrder 
{
    // ...snip...
}
```

The derived impls require that the type traits also implement the trait.

If `ByteOrder` implied `Eq`, `Clone`, `Copy`, etc... the problems would go away. Arguably, this is a bug in the `#[derive(Foo)]` expansion code for not understanding `PhantomData`, but adding this would work around that bug.

Since one can't even instantiate `BigEndian` or `LittleEndian`, all the impls could be `unreachable!()`.

Would you be willing to accept a patch that does this?

**Comment by BurntSushi** [comment]
@fitzgen Sorry for not responding earlier, but I think your suggestion sounds fine. I don't think it will cause any massive breaking changes either (because I don't really expect any impls of `ByteOrder` other than what's defined in this crate).

**Comment by Ericson2314** [comment]
Would it be possible to fix derive? The default inpl for the empty enums is unfortunate and it would be a shame to see that baked in for 1.0.

**Comment by BurntSushi** [comment]
> The default inpl for the empty enums is unfortunate and it would be a shame to see that baked in for 1.0.

@Ericson2314 Why? Can you please expand on this?

**Comment by BurntSushi** [comment]
> The default inpl for the empty enums is unfortunate and it would be a shame to see that baked in for 1.0.

@Ericson2314 Why? Can you please expand on this? Note that it has [already happened](https://docs.rs/byteorder/1.0.0/byteorder/enum.BigEndian.html).

**Comment by Ericson2314** [comment]
Oh didn't realize it did oops. It's unfortunate because Default is only supposed to be implemented by inhabited types. Funtions that are never save to call shouldn't exist.

**Comment by BurntSushi** [comment]
Seems like a mostly theoretical downside to me.

**Comment by Ericson2314** [comment]
Perhaps, but I'm of the view that small theoretical cuts do add up. Anyways now that 1.0 has happened, I should probably open a rust issue or something.
