### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by KallDrexx** [BurntSushi/byteorder#53]
The documentation at http://burntsushi.net/rustdoc/byteorder seems to be outdated.  The biggest issue that really confused me was that the Error type was removed (http://burntsushi.net/rustdoc/byteorder/enum.Error.html).

**Comment by BurntSushi** [comment]
Yup, I'm working on getting this fixed. Thanks for the report!

**Comment by BurntSushi** [comment]
Should be fixed now! Thanks again!

**Comment by KallDrexx** [comment]
Much appreciated.  Love the library!
