### ISSUE TITLE
approaching 1.0

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/byteorder#54]
`byteorder` is very heavily used, but its API has mostly remained the same since it was first released (which was inspired by both Go's `encoding/binary` package and the pre-existing methods in Rust's old standard library that fulfilled a similar role). There was however significant discussion on its API in #27, but I feel that no consensus has been reached and I don't think there's an obviously better API given Rust in its current form. Therefore, I'd like to propose that we cut a 1.0 release in the next few weeks.

I think the only outstanding issue that we should try to resolve before 1.0 is #52.

cc @nwin @TyOverby @sfackler @lambda

**Comment by sfackler** [comment]
The biggest thing I'd like is a less verbose way to select endianness. Having to stick `::<BigEndian>` everywhere is a bit of a bummer. The old stdlib `foo_be` and `foo_le` seem nicer in that sense, or maybe even separate traits for the different endiannesses?

**Comment by nwin** [comment]
@sfackler Then you'd have the problem, that you couldn't specialize over the endianess at compile time any more. Therefore the method name has to stay the same. My proposal in #27 was even worse in this regard. 

@BurntSushi I agree we should see that we fix issues like #52 and stabilize a 1.0. Then we could even start a 2.x playground.

**Comment by BurntSushi** [comment]
Yeah, #27 was precisely where we tried to fix that. Another problem with the `foo_be` and `foo_le` approach is that it doesn't offer a nice way of using "native" endianness, where as today we get it pretty easily with a platform dependent type synonym. We could create `foo_native`, but that seems gratuitous. Similarly, we could offer `foo_be`/`foo_le` *in addition* to the current API, but I really feel like having lots of different ways to read/write integers is bad (the API already has two).

Something I normally is `use byteorder::{ReadBytesExt, LittleEndian as LE}` which lets me say `rdr.read_u32::<LE>()`, which is a little nicer.

**Comment by ticki** [comment]
Here's what I'd suggest:

Instead of `read_*` and `write_*` methods, there should be one unified trait for encodable integers, and made generic such that some downstream user can implement it for custom integer types, but also abstract over different integer types.

Secondly, I think this simplifies implementation of #58 a lot.

**Comment by BurntSushi** [comment]
@ticki Did you read #27?

I'm not especially inclined to completely scrap the current API for `1.0`.

**Comment by ticki** [comment]
> I'm not especially inclined to completely scrap the current API for 1.0.

Can I ask: why not? Wildcard dependencies are banned on crates.io now, so the breakage should be really small (is there a breakage at all?).

**Comment by BurntSushi** [comment]
Because I'd like the upgrade process to be smooth. `byteorder` has been basically unchanged for literally *years*. It's time to commit to the current API and stabilize at `1.0`.

If there's a better API (and it isn't at all clear that there is), then that can be iterated on for `2.0` or even in a new crate.

**Comment by ticki** [comment]
[ew wtf](https://crates.io/crates/byteorder/reverse_dependencies)

**Comment by ticki** [comment]
A lot of those are `*` depedencies.

**Comment by ticki** [comment]
I'm going to sit down and see what I can come up with in one of the next days.

**Comment by BurntSushi** [comment]
The presence of absence of `*` in reverse dependencies doesn't really carry a lot influence for me at this point.

**Comment by BurntSushi** [comment]
@ticki Since I haven't heard any acknowledgment from you otherwise, I'm going to ask again: have you read #27?

**Comment by ticki** [comment]
Only skimmed the first half of the thread. I'll read the rest.

**Comment by whitequark** [comment]
@BurntSushi Any updates on 1.0? I would like to get rid of the 'dependency' on kernel32-sys :)

**Comment by whitequark** [comment]
@BurntSushi Nevermind, sorry, that was meant for `walkdir` and you already released 1.0.

**Comment by BurntSushi** [comment]
@whitequark No worries. I hope to push `byteorder` to 1.0 and a few other crates this weekend.

**Comment by BurntSushi** [comment]
Done in https://github.com/BurntSushi/byteorder/commit/7f90e282f629f2864d7fc14640ea710dab6ddc95 w00t!
