### ISSUE TITLE
consider returning number of bytes written in WriteBytesExt methods

### ISSUE THREAD

**Issue by tones111** [BurntSushi/byteorder#55]
While this sounds redundant because the write methods are designed for fixed-width types it would allow the caller to more easily compute the amount of data written.  As an example use case, consider sending a small packet of data over a UDP socket.  Something like:

let mut buf = [0u8; 16];
let mut n = 0;
{
    let mut packet = &mut buf[..];
    n += try!(packet.write_u16::<BigEndian>(1u16));
    n += try!(packet.write_u16::<BigEndian>(2u16));
    n += try!(packet.write_u16::<BigEndian>(3u16));
}
let sock = try!(std::net::UdpSocket::bind("0.0.0.0:0"));
try!(sock.send_to(&buf[..n], "127.0.0.1:1234"));

It gets harder to determine how many bytes may have been written for increasingly complicated packets (perhaps with conditional/variable length fields).  Or if new fields are added in the future there is less risk of the sent buffer size not getting updated to match.  Writing into a vector would also provide the necessary book keeping but requires an allocation from the heap.  This would also bring the API closer in line with the std::io::Write's write signature.

Is there much of a performance hit in returning a hard-coded usize value instead of the empty tuple?

**Comment by BurntSushi** [comment]
> Is there much of a performance hit in returning a hard-coded usize value instead of the empty tuple?

My guess is that there's probably no performance hit in release builds.

This is kind of a small issue, but it feels really weird to me to return fixed integers in an API like this, and I think the type signature might surprise a lot of people. I do agree that it will make *some* use cases nicer, but I might also argue that those are the job of a higher level API.

**Comment by whitequark** [comment]
But there's already a (sort of) this higher level API. I believe you could use the `impl<'a> Write for Cursor<&'a mut [u8]>`, and then query the position of the cursor when you need it.

**Comment by BurntSushi** [comment]
I'm going to close this. While I think it could make some use cases a little nicer, I personally would find the type signature surprising. I'd prefer that callers define a helper function when this type of API is useful.
