### ISSUE TITLE
i24 (traid) support

### ISSUE THREAD

**Issue by mhsjlw** [BurntSushi/byteorder#56]
Please add support for the 24 byte int (little, big, signed, unsigned) 

In most cases, this is how i24s are implemented:

### Writing
1. Start with an int, lets say 0 (`0x00`, `0x00`, `0x00`, `0x00`)
2. Take the last byte off of the int to make it `0x00`, `0x00`, `0x00`

### Reading
1. Get `0x00`, `0x00`, `0x00` and just pad it with another null byte then read it as an int (`0x00`, `0x00`, `0x00`, `0x00`)

**Comment by BurntSushi** [comment]
@mhsjlw Could you please describe why [`ByteOrder::write_uint`](http://burntsushi.net/rustdoc/byteorder/trait.ByteOrder.html#tymethod.write_uint) and [`ByteOrder::read_uint`](http://burntsushi.net/rustdoc/byteorder/trait.ByteOrder.html#tymethod.read_uint) are insufficient?

**Comment by BurntSushi** [comment]
@mhsjlw Could you please describe why [`ByteOrder::write_uint`](http://burntsushi.net/rustdoc/byteorder/trait.ByteOrder.html#tymethod.write_uint) and [`ByteOrder::read_uint`](http://burntsushi.net/rustdoc/byteorder/trait.ByteOrder.html#tymethod.read_uint) are insufficient?

**Comment by BurntSushi** [comment]
@mhsjlw Could you please describe why [`ByteOrder::write_uint`](http://burntsushi.net/rustdoc/byteorder/trait.ByteOrder.html#tymethod.write_uint) and [`ByteOrder::read_uint`](http://burntsushi.net/rustdoc/byteorder/trait.ByteOrder.html#tymethod.read_uint) are insufficient?

**Comment by mhsjlw** [comment]
Not only would an in-library implementation be easier to understand (for someone reading your code) but it would also make it much easier when you need to write little or big endian triads rather than writing your own implementation in-house. If it is just me who wants i24s, I understand that there is no demand and I'll probably just add it myself. Although I think it'd be a useful feature to have.

**Comment by mhsjlw** [comment]
Not only would an in-library implementation be easier to understand (for someone reading your code) but it would also make it much easier when you need to write little or big endian triads rather than writing your own implementation in-house. If it is just me who wants i24s, I understand that there is no demand and I'll probably just add it myself. Although I think it'd be a useful feature to have.

**Comment by BurntSushi** [comment]
> rather than writing your own implementation in-house

I don't understand. You don't need to do this. `read_uint(buf, 3)` seems like it should be sufficient, no?

**Comment by mhsjlw** [comment]
Oh wow... I was unaware it was this simple. Thank you very much. How could I make this little endian as well?

**Comment by BurntSushi** [comment]
@mhsjlw The [examples](http://burntsushi.net/rustdoc/byteorder/#examples) should help. :-) If you're reading from an `io::Read`, then use `rdr.read_uint::<LittleEndian>(3)`. If you're reading straight from a buffer, then `LittleEndian::read_uint(buf, 3)`.
