### ISSUE TITLE
Question:  Reading in an arbitrarily number of bytes

### ISSUE THREAD

**Issue by superhac** [BurntSushi/byteorder#64]
Thanks for the great work in creating this library!  it has been working great for me.   I do have one question though.   How does one read arbitrarily amount of bytes?  E.g. not a fixed size.   For example I want to read 6 bytes and put it into an [u8;6] array.

Thanks,

Superhac

**Comment by BurntSushi** [comment]
I don't understand the question. This library is about encoding and decoding integers, with some convenience routines on Write and Read impls. It doesn't sound like you're converting integers?

Could you please include some code and say more about the specific problem you're trying to solve?

**Comment by superhac** [comment]
I figured it out.   I didn't understand what the "Cursor" object was in the example.   I was able to do this directly via std::io.  

buf.read_exact(&mut head.version).expect("head.version");

Its all good now.  Thanks anyways!
