### ISSUE TITLE
Add wrapper for `ReadBytesExt`/`WriteBytesExt` which stores the endianness

### ISSUE THREAD

**Issue by abonander** [BurntSushi/byteorder#67]
Using `ReadBytesExt` is very noisy due to having to specify the endianness in every call:

```rust
let foo = reader.read_u16::<BigEndian>()?;
let bar = reader.read_u16::<BigEndian>()?;
let baz = reader.read_u32::<BigEndian>()?;
```

It would be nice if there was a reader adapter which stored the endianness to DRY this up:

```rust
pub struct ReadBytes<R, E> {
    inner: R,
    endianness: PhantomData<E>
}

impl<R, E> ReadBytes where R: Read, E: ByteOrder {
    // Alternately place this as an adapter method on `ReadBytesExt`
    pub fn new(inner: R) -> Self {...}

    // Duplicate methods of `ReadBytesExt` without the endianness parameter
}
```

Of course, all of this applies to `WriteBytesExt` as well.

**Comment by BurntSushi** [comment]
Dupe of #27.

I'm not really interested in expanding the API. It's already too complex. I don't want multiple ways of doing something just for the sake of DRY. I am, and always have been, open to redesign, but it was already hashed out in #27.

Consider using `use byteorder::BigEndian as BE` to reduce typing.

**Comment by abonander** [comment]
I don't consider this a duplicate of #27, as that appeared to mainly address reducing the number of methods in the API. All proposed changes still required specifying the byte order for every call, even though that's the one thing that's most unlikely to change over the lifetime of a given reader. Additionally, my proposal here would be backwards-compatible for all current usage.

**Comment by BurntSushi** [comment]
OK, fine. I'll reword:

> I'm not really interested in expanding the API. It's already too complex. I don't want multiple ways of doing something just for the sake of DRY. I am, and always have been, open to redesign

**Comment by abonander** [comment]
I don't have have a redesign to propose. This API isn't anywhere near "complex" on the spectrum, and I think you're dismissing the importance of good ergonomics too easily. However, you've made your preferences clear so I'll consider the matter closed.
