### ISSUE TITLE
Incorrect use of unreachable!()

### ISSUE THREAD

**Issue by dtolnay** [BurntSushi/byteorder#68]
```rust
extern crate byteorder;

fn main() {
    byteorder::LittleEndian::default();
}
```

```
thread 'main' panicked at 'internal error: entered unreachable code'
```

Unreachable doesn't mean "please don't call this," it means "you can't get here." I think it is okay for this method to panic but it should be something other than unreachable. A handwritten message explaining why this method exists would be nice.

cc @fitzgen

**Comment by frewsxcv** [comment]
Why does this `Default` implementation need to exist?

**Comment by BurntSushi** [comment]
@frewsxcv So that it works with `derive` seamlessly. See #52.
