### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by brson** [BurntSushi/byteorder#75]
Several types do not directly contain examples, nor do many methods. It's not clear how much example coverage we need, the policy in std though is for everything to have an example.

**Comment by BurntSushi** [comment]
@steveklabnik What are your thoughts on this for a crate like byteorder? If you take a look at the [`ByteOrder`](https://docs.rs/byteorder/1.0.0/byteorder/trait.ByteOrder.html) trait, there are many methods that essentially do the same thing with differently sized integers. Are a few examples on the trait sufficient? Or do you think we should literally have an example for every method?

**Comment by steveklabnik** [comment]
I personally prefer literally an example for every method, even if they're very similar. Users really like being able to look at the docs, copy/paste something, and get it going. IMHO that outweighs stuff looking similar.

**Comment by BurntSushi** [comment]
I think we got this covered by several PRs merged recently.
