### ISSUE TITLE
Working with arrays

### ISSUE THREAD

**Issue by Kixunil** [BurntSushi/byteorder#96]
Current implementation uses `&[u8]` for reading and `&mut [u8]` for writing, which panics if lengths are invalid. I suggest to implement alternative functions like `read_arr_u16(but: &[u8; 2])` (name subject to bike shedding), that would take reference to array.

This would come handy in combination with constant generics, where code could guarantee absence of panics (due to programmer error) and elision of (unnecessary) checks.

Once constant generics are in Rust, the old (`&[u8]`) versions could be implemented using new ones. I guess this could be done with macros.

**Comment by BurntSushi** [comment]
I think I would need to insist on seeing a benchmark and/or generated code
to justify this. It seems like if you have an array, then the optimizer
should see through that and elide bounds checks, no?

**Comment by Kixunil** [comment]
If the function inlines, then yes. Seems like I didn't make myself clear that I was referring to statically proving that the code can't panic.

I prefer discovering bugs during compilation.

**Comment by BurntSushi** [comment]
Yeah, I'm not on board with that. I don't value your safety above everything else. In this case, you're talking about doubling the size of the current API.

When const generics lands, we can revisit this.

**Comment by Kixunil** [comment]
OK, thanks for reply!
